title: Thatway1989的博客
description: Port of the Read the Docs theme to Jekyll to use with GitHub Pages.
remote_theme: thatway1989/thatway1989.github.io

# Theme settings:
site_author: Thatway1989
repo_url: "https://github.com/thatway1989/thatway1989.github.io"
edit_on_github: true
github_docs_folder: true
sticky_navigation: true
prev_next_buttons_location: both
search_enabled: true
hljs_style: github-gist
